### ISSUE TITLE
SubQuery & PageRequest : wrong alias used for sort

### ISSUE THREAD

**Issue by MarneusCalgarXP** [spring-projects/spring-data-jpa#2518]
bug occurs in version : spring-data-jpa 2.6.4 (was ok in 2.6.3 and prior versions)

sample project to reproduce:

Model : 
```java
@Entity
public class Foo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

}
```

Repository : 
```java
public interface FooRepository extends JpaRepository<Foo, Long> {

    @Query("SELECT f" +
            " FROM com.example.demo.model.Foo f " +
            "WHERE f.id = ( " +
            "    SELECT MIN(g.id)" +
            "    FROM com.example.demo.model.Foo g " +
            " ) ")
    Page<Foo> findCustomFoo(Pageable pageable);

}
```

call :
```java
Page<Foo> page = fooRepository.findCustomFoo(
	PageRequest.of(0, 10, Sort.Direction.ASC, "id")
);
```

HQL generated in versions prior to 2.6.3 (included)
```
SELECT f FROM com.example.demo.model.Foo f WHERE f.id = ( SELECT MIN(g.id) FROM com.example.demo.model.Foo g ) 
order by f.id asc
```

HQL generated in version 2.6.4
```
SELECT f FROM com.example.demo.model.Foo f WHERE f.id = ( SELECT MIN(g.id) FROM com.example.demo.model.Foo g ) 
order by g.id asc
```

==> the alias used in `order by` points to the subquery table, which is not available at global level

which leads to a `QuerySyntaxException` :
```
org.hibernate.hql.internal.ast.QuerySyntaxException: 
Invalid path: 'g.id' 
[SELECT f FROM com.example.demo.model.Foo f WHERE f.id = (     SELECT MIN(g.id)    FROM com.example.demo.model.Foo g  )  order by g.id asc]
```

**Comment by DiegoKrupitza** [comment]
I think this should be fixed with PR #2516 by @darinmanica.

**Comment by darinmanica** [comment]
I agreed, @DiegoKrupitza.  PR #2516 should resolve this issue, making this issue a duplicate of #2500 and the second half of #2260.  @MarneusCalgarXP feel free to pull the PR and test with your examples.  I was able to replace the 2.6.4 builds with the PR builds to make everything work again.

**Comment by MarneusCalgarXP** [comment]
@darinmanica I copied the QueryUtils.java file in my project from PR https://github.com/spring-projects/spring-data-jpa/pull/2516 , everything is OK, problem solved

**Comment by alexantonica** [comment]
Still happening in 2.7.1. I've just upgraded from 2.6.3 and this started failing. 
[Stackoverflow post](https://stackoverflow.com/questions/73645714/query-broken-after-spring-boot-upgrade-from-2-6-x-to-2-7-x)
