### ISSUE TITLE
FilterDef and Filter annotations not working after upgrade.

### ISSUE THREAD

**Issue by achris001c** [spring-projects/spring-data-jpa#2565]
Previous Dependency Versions:
- Spring boot v2.1.2, Spring data JPA v2.1.4 , Hibernate 5.3.7.Final
 
Upgraded Dependency Versions:
- Spring boot v2.5.12, spring data jpa v2.5.10, Hibernate v5.4.33

Query Generation with earlier version (Repository.getById()): 
Hibernate: select useraccoun0_.id as id1_2_, useraccoun0_.tenant_id as tenant_i4_2_, useraccoun0_.first_name as first_na2_2_, useraccoun0_.last_name as last_nam3_2_ from user_account useraccoun0_ where **useraccoun0_.tenant_id = ?** and useraccoun0_.id=?

Query Generation after upgrade (Repository.getById()):
Hibernate: select useraccoun0_.id as id1_2_0_, useraccoun0_.tenant_id as tenant_i4_2_0_, useraccoun0_.first_name as first_na2_2_0_, useraccoun0_.last_name as last_nam3_2_0_ from user_account useraccoun0_ where useraccoun0_.id=?

**Comment by achris001c** [comment]
Filters Working Code Base : https://github.com/achris001c/MultiTenantService/tree/working

Code Base where Filters don't work : https://github.com/achris001c/MultiTenantService/tree/not-working

Dependencies on "working" branch: Spring boot v2.1.2, Spring data JPA v2.1.4 , Hibernate 5.3.7.Final
Dependencies on "not-working" branch : Spring boot v2.5.12, spring data jpa v2.5.10, Hibernate v5.4.33

**Comment by derekm** [comment]
@achris001c -- Was this ever fixed? Are FilterDefs no longer supported?

**Comment by derekm** [comment]
@schauder -- The reporter of this issue closed their own issue after 2 days, and this loss of functionality was never addressed by the project. Closing this issue appears to have been a mistake. Their "minimally reproducible example" shows this not working all the way up to 2.7.

Someone else has gone out of their way to restore this functionality for themselves: https://babystepstopro.medium.com/adding-hibernate-entity-level-filtering-feature-to-spring-data-jpa-repository-76bf8ddd42ff

Somewhere between Spring Boot 2.1 and 2.5, Spring stopped creating JpaRepository queries through EntityManager?

Can this functionality be brought back in Spring Boot 3.x? We can unwrap our own Sessions and enable our own filters in our own Service layers. Spring Boot has a hard dependency on Hibernate, so why not restore this feature?

**Comment by schauder** [comment]
I'm reopening this so someone can take a look what is going on. 

> Somewhere between Spring Boot 2.1 and 2.5, Spring stopped creating JpaRepository queries through EntityManager?

All queries executed by Spring Data JPA go through the `EntityManager`, so that's most certainly not the reason. I currently have no idea what is.

**Comment by marcioggs** [comment]
I'm using Hibernate 6.5.5 and had to add the `autoEnabled` property after the upgrade for it to work like before on Spring Data JPA.

```java
@FilterDef(name = "FILTER_NAME", autoEnabled = true)
```

I didn't find any related instruction in the Hibernate migration guides.

**Comment by smaelc** [comment]
I'm facing this issue and i still have a raised exception. 
```java
@FilterDef(name = "ShowDeletedFilter"
	, autoEnabled = true
	, parameters = @ParamDef(
	name = "showDeleted", type = Boolean.class),  defaultCondition = """
	(:showDeleted = true OR deleted = false)
""")
@SQLRestriction("deleted <> true")
public abstract class AuditableEntity {}
```
into my PostEntity class file

```java
@Filter(name = "ShowDeletedFilter") // Not executed or not working
public class PostEntity extends AuditableEntity {}
```

IT
```java
@DataJpaTest
class FindByIdAndDeleteIT {

  @Autowired
  TestEntityManager testEntityManager;

  @Test
  void shouldBePhysicallyPresentAfterLogicallyDeleteIt(){
  
        // I wanna see the deleted entry from database
        testEntityManager.getEntityManager().unwrap(Session.class)
        		.enableFilter("ShowDeletedFilter").setParameter("showDeleted", Boolean.TRUE);
  
  	PostEntity entity = new PostEntity();
  	entity.setTitle("title");
  	entity.setContent("content");
  	entity.setCreatedBy(UUID.randomUUID());
  	entity.setUpdatedBy(UUID.randomUUID());
  	entity.setCreatedOn(Instant.now());
  	entity.setUpdatedOn(Instant.now());
  
  	testEntityManager.persistAndFlush(entity);
  	assertThat(entity).isNotNull().extracting(PostEntity::isDeleted).isEqualTo(Boolean.FALSE);
  
  	UUID id = entity.getId();
  	testEntityManager.remove(entity);
  	testEntityManager.flush();
  
     // Raise NoSuchElementException here
  	PostEntity deletedEntity = assertDoesNotThrow(()-> repository.findById(id).orElseThrow()); 

  	assertThat(deletedEntity).isNotNull().extracting(PostEntity::isDeleted).isEqualTo(Boolean.TRUE);
  }
}
```
debug => "........ where pe1_0.uid=?" 
NOT PRESENT SQL => "..... where pe1_0.uid=? or deleted = :showDeleted or deleted = false"

Helps !!!

**Comment by smaelc** [comment]
And if i remove @SqlRestiction, i still see the deleted entries because, NOT PRESENT SQL => "..... where pe1_0.uid=? or deleted = :showDeleted or deleted = false"
