### ISSUE TITLE
nativeQuery "SELECT * FROM [...]" in parent interface throws grammar exception

### ISSUE THREAD

**Issue by Andrei-Paul** [spring-projects/spring-data-jpa#3096]
We have:
```java
// EDIT: UPDATED

public interface GenericRepository<E extends AbstractEntity, ID> extends JpaRepository<E, ID> {
    @Query(value = "SELECT * FROM #{#entityName} ORDER BY `Id` ASC LIMIT :index, 1", nativeQuery = true)
    E findAtMost1(Integer index);
}

public interface ConcreteRepository extends GenericRepository<ConcreteEntity, UUID> {
}

public abstract class AbstractService<E extends AbstractEntity> implements GenericService<E> {
    GenericRepository<E, Object> repo;
    Integer Index = -1;

    public AbstractService(GenericRepository repo) {
        this.repo = repo;
    }

    @Override
    public E findAtMost1() {
        this.oneIndex++;
        return this.repo.findAtMost1(index);
    }
}

@Service
public class ConcreteService extends AbstractService<ConcreteEntity> {

    @Autowired
    ConcreteRepository repo;

    public ConcreteService(ConcreteRepository repo) {
        super(repo);
        this.repo = repo;
    }
}
```
If we call:
```java
@Autowired
ConcreteService concreteService;
// ...
concreteEntity = concreteService.findAtMost1(0);
```
With 3.1.2 it results in:

<code>org.springframework.dao.InvalidDataAccessApiUsageException: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:7 extraneous input '*' expecting {'(', '{', '+', '-', ':', '?', ALL, AND, ANY, AS, ASC, AVG, BETWEEN, BOTH, BREADTH, BY, CASE, CAST, COLLATE, COUNT, CROSS, CUBE, CURRENT, CURRENT_DATE, CURRENT_INSTANT, CURRENT_TIME, CURRENT_TIMESTAMP, CYCLE, DATE, DATETIME, DAY, DEFAULT, DELETE, DEPTH, DESC, DISTINCT, ELEMENT, ELEMENTS, ELSE, EMPTY, END, ENTRY, EPOCH, ERROR, ESCAPE, EVERY, EXCEPT, EXCLUDE, EXISTS, EXTRACT, FALSE, FETCH, FILTER, FIRST, FLOOR, FOLLOWING, FOR, FORMAT, FROM, FULL, FUNCTION, GROUP, GROUPS, HAVING, HOUR, ID, IGNORE, ILIKE, IN, INDEX, INDICES, INNER, INSERT, INSTANT, INTERSECT, INTO, IS, JOIN, KEY, LAST, LEADING, LEFT, LIKE, LIMIT, LIST, LISTAGG, LOCAL, LOCAL_DATE, LOCAL_DATETIME, LOCAL_TIME, MAP, MATERIALIZED, MAX, MAXELEMENT, MAXINDEX, MEMBER, MICROSECOND, MILLISECOND, MIN, MINELEMENT, MININDEX, MINUTE, MONTH, NANOSECOND, NATURALID, NEW, NEXT, NO, NOT, NULL, NULLS, OBJECT, OF, OFFSET, OFFSET_DATETIME, ON, ONLY, OR, ORDER, OTHERS, OUTER, OVER, OVERFLOW, OVERLAY, PAD, PARTITION, PERCENT, PLACING, POSITION, PRECEDING, QUARTER, RANGE, RESPECT, RIGHT, ROLLUP, ROW, ROWS, SEARCH, SECOND, SELECT, SET, SIZE, SOME, SUBSTRING, SUM, THEN, TIES, TIME, TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE, TO, TRAILING, TREAT, TRIM, TRUE, TRUNC, TRUNCATE, TYPE, UNBOUNDED, UNION, UPDATE, USING, VALUE, VALUES, VERSION, VERSIONED, WEEK, WHEN, WHERE, WITH, WITHIN, WITHOUT, YEAR, CHARACTER, STRINGLITERAL, JAVASTRINGLITERAL, INTEGER_LITERAL, FLOAT_LITERAL, HEXLITERAL, BINARY_LITERAL, IDENTIFICATION_VARIABLE}; Bad JPQL grammar [SELECT * FROM ConcreteEntityTable ORDER BY `Id` ASC LIMIT :index, 1]
 at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
 at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:234)
 at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
 at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
 at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
 at jdk.proxy2/jdk.proxy2.$Proxy137.findAtMost1(Unknown Source)
 at test.example.logic.concrete.AbstractService.getOne(AbstractService.java:46)
 at test.example.ConcreteEntityTests.get_ConcreteEntityTableService(ConcreteEntityTests.java:214)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)

Caused by: java.lang.IllegalArgumentException: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:7 extraneous input '*' expecting {'(', '{', '+', '-', ':', '?', ALL, AND, ANY, AS, ASC, AVG, BETWEEN, BOTH, BREADTH, BY, CASE, CAST, COLLATE, COUNT, CROSS, CUBE, CURRENT, CURRENT_DATE, CURRENT_INSTANT, CURRENT_TIME, CURRENT_TIMESTAMP, CYCLE, DATE, DATETIME, DAY, DEFAULT, DELETE, DEPTH, DESC, DISTINCT, ELEMENT, ELEMENTS, ELSE, EMPTY, END, ENTRY, EPOCH, ERROR, ESCAPE, EVERY, EXCEPT, EXCLUDE, EXISTS, EXTRACT, FALSE, FETCH, FILTER, FIRST, FLOOR, FOLLOWING, FOR, FORMAT, FROM, FULL, FUNCTION, GROUP, GROUPS, HAVING, HOUR, ID, IGNORE, ILIKE, IN, INDEX, INDICES, INNER, INSERT, INSTANT, INTERSECT, INTO, IS, JOIN, KEY, LAST, LEADING, LEFT, LIKE, LIMIT, LIST, LISTAGG, LOCAL, LOCAL_DATE, LOCAL_DATETIME, LOCAL_TIME, MAP, MATERIALIZED, MAX, MAXELEMENT, MAXINDEX, MEMBER, MICROSECOND, MILLISECOND, MIN, MINELEMENT, MININDEX, MINUTE, MONTH, NANOSECOND, NATURALID, NEW, NEXT, NO, NOT, NULL, NULLS, OBJECT, OF, OFFSET, OFFSET_DATETIME, ON, ONLY, OR, ORDER, OTHERS, OUTER, OVER, OVERFLOW, OVERLAY, PAD, PARTITION, PERCENT, PLACING, POSITION, PRECEDING, QUARTER, RANGE, RESPECT, RIGHT, ROLLUP, ROW, ROWS, SEARCH, SECOND, SELECT, SET, SIZE, SOME, SUBSTRING, SUM, THEN, TIES, TIME, TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE, TO, TRAILING, TREAT, TRIM, TRUE, TRUNC, TRUNCATE, TYPE, UNBOUNDED, UNION, UPDATE, USING, VALUE, VALUES, VERSION, VERSIONED, WEEK, WHEN, WHERE, WITH, WITHIN, WITHOUT, YEAR, CHARACTER, STRINGLITERAL, JAVASTRINGLITERAL, INTEGER_LITERAL, FLOAT_LITERAL, HEXLITERAL, BINARY_LITERAL, IDENTIFICATION_VARIABLE}; Bad JPQL grammar [SELECT * FROM ConcreteEntityTable ORDER BY `Id` ASC LIMIT :index, 1]
 at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:56)
 at org.springframework.data.jpa.repository.query.JpaQueryEnhancer.applySorting(JpaQueryEnhancer.java:88)
 at org.springframework.data.jpa.repository.query.JpaQueryEnhancer.applySorting(JpaQueryEnhancer.java:100)
 at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.doCreateQuery(AbstractStringBasedJpaQuery.java:96)
 at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:234)
 at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:223)
 at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
 at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148)
 at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
 ... 79 more
Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:7 extraneous input '*' expecting {'(', '{', '+', '-', ':', '?', ALL, AND, ANY, AS, ASC, AVG, BETWEEN, BOTH, BREADTH, BY, CASE, CAST, COLLATE, COUNT, CROSS, CUBE, CURRENT, CURRENT_DATE, CURRENT_INSTANT, CURRENT_TIME, CURRENT_TIMESTAMP, CYCLE, DATE, DATETIME, DAY, DEFAULT, DELETE, DEPTH, DESC, DISTINCT, ELEMENT, ELEMENTS, ELSE, EMPTY, END, ENTRY, EPOCH, ERROR, ESCAPE, EVERY, EXCEPT, EXCLUDE, EXISTS, EXTRACT, FALSE, FETCH, FILTER, FIRST, FLOOR, FOLLOWING, FOR, FORMAT, FROM, FULL, FUNCTION, GROUP, GROUPS, HAVING, HOUR, ID, IGNORE, ILIKE, IN, INDEX, INDICES, INNER, INSERT, INSTANT, INTERSECT, INTO, IS, JOIN, KEY, LAST, LEADING, LEFT, LIKE, LIMIT, LIST, LISTAGG, LOCAL, LOCAL_DATE, LOCAL_DATETIME, LOCAL_TIME, MAP, MATERIALIZED, MAX, MAXELEMENT, MAXINDEX, MEMBER, MICROSECOND, MILLISECOND, MIN, MINELEMENT, MININDEX, MINUTE, MONTH, NANOSECOND, NATURALID, NEW, NEXT, NO, NOT, NULL, NULLS, OBJECT, OF, OFFSET, OFFSET_DATETIME, ON, ONLY, OR, ORDER, OTHERS, OUTER, OVER, OVERFLOW, OVERLAY, PAD, PARTITION, PERCENT, PLACING, POSITION, PRECEDING, QUARTER, RANGE, RESPECT, RIGHT, ROLLUP, ROW, ROWS, SEARCH, SECOND, SELECT, SET, SIZE, SOME, SUBSTRING, SUM, THEN, TIES, TIME, TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE, TO, TRAILING, TREAT, TRIM, TRUE, TRUNC, TRUNCATE, TYPE, UNBOUNDED, UNION, UPDATE, USING, VALUE, VALUES, VERSION, VERSIONED, WEEK, WHEN, WHERE, WITH, WITHIN, WITHOUT, YEAR, CHARACTER, STRINGLITERAL, JAVASTRINGLITERAL, INTEGER_LITERAL, FLOAT_LITERAL, HEXLITERAL, BINARY_LITERAL, IDENTIFICATION_VARIABLE}; Bad JPQL grammar [SELECT * FROM ConcreteEntityTable ORDER BY `Id` ASC LIMIT :index, 1]
 at org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
 at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
 at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
 at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
 at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
 at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
 at org.springframework.data.jpa.repository.query.HqlParser.selectClause(HqlParser.java:3577)
 at org.springframework.data.jpa.repository.query.HqlParser.query(HqlParser.java:1194)
 at org.springframework.data.jpa.repository.query.HqlParser.orderedQuery(HqlParser.java:1068)
 at org.springframework.data.jpa.repository.query.HqlParser.queryExpression(HqlParser.java:454)
 at org.springframework.data.jpa.repository.query.HqlParser.selectStatement(HqlParser.java:387)
 at org.springframework.data.jpa.repository.query.HqlParser.ql_statement(HqlParser.java:318)
 at org.springframework.data.jpa.repository.query.HqlParser.start(HqlParser.java:256)
 at org.springframework.data.jpa.repository.query.HqlQueryParser.parseQuery(HqlQueryParser.java:53)
 at org.springframework.data.jpa.repository.query.HqlQueryParser.parse(HqlQueryParser.java:63)
 at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$new$0(JpaQueryParserSupport.java:182)
 at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
 at org.springframework.data.util.Lazy.get(Lazy.java:114)
 at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
 at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:54)
 ... 99 more</code>

**Comment by gregturn** [comment]
Looks like the `nativeQuery` attribute isn't being passed along from your generic repository to the concrete one, because somehow this query is being routed into the JPQL parser, when it shouldn't.

**Comment by gregturn** [comment]
Since this appears to be an abstract base, what happens if you apply `@NoRepositoryBean` to this interface definition?

See https://docs.spring.io/spring-data-commons/reference/repositories/definition.html#repositories.definition-tuning for more details.

**Comment by Andrei-Paul** [comment]
Same result.

I've updated the example code.

I just checked with 3.0.4, 3.0.9 and it works, but 3.1.2 throws exception.

**Comment by gregturn** [comment]
It looks like the processing of `select * from #{#entityName}` -> `select * from Employee` is where it loses the `isNative=true` attribute.

```java
	public ExpressionBasedStringQuery(String query, JpaEntityMetadata<?> metadata, SpelExpressionParser parser,
			boolean nativeQuery) {
		super(renderQueryIfExpressionOrReturnQuery(query, metadata, parser), nativeQuery && !containsExpression(query));
	}
```
Looks like that additional `!containsExpression(query)` is where the `nativeQuery` aspect gets lost, hence steering it into the grammar parser.

**Comment by gregturn** [comment]
Okay, to further clarify, this is due to our SpEL processing rules, NOT having a generic base repository. The following repository definition generates the same situation:

```java
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

	@Query(value = "select * from #{#entityName}", nativeQuery = true)
	List<Employee> custom();
}
```
This is purely because we CURRENTLY transform a SpEL expression into a non-native query, which I'm trying to dig in and see why that is the case. Because in this context, it doesn't make sense.

**Comment by lSeneka** [comment]
Hello.
Are any continuations expected? Or issues has been solved somewhere else?

**Comment by mp911de** [comment]
This has been fixed since version 3.2.3.

**Comment by marcinpiwko** [comment]
Not exactly fixed.

For simple (List) cases it maybe works but mixing native query with pagination still results in error. Code example:

```java
@NoRepositoryBean
public interface SoftDeleteRepository<K extends SoftDeleteEntity> extends VersionableRepository<K> {

  @Query(value = "SELECT * FROM #{#entityName} WHERE AUDIT_RD IS NOT NULL", nativeQuery = true)
  Page<K> findDeletedEntities(Pageable pageable);
}
```

When pageable has default attributes (eg. page=0), query works fine but manipulating pagination ends with:

``
Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:7 extraneous input '*' expecting {'(', '{', '+', '-', ':', '?', ALL, AND, ANY, AS, ASC, AVG, BETWEEN, BOTH, BREADTH, BY, CASE, CAST, COLLATE, CONTAINS, COUNT, CROSS, CUBE, CURRENT, CURRENT_DATE, CURRENT_INSTANT, CURRENT_TIME, CURRENT_TIMESTAMP, CYCLE, DATE, DATETIME, DAY, DEFAULT, DELETE, DEPTH, DESC, DISTINCT, ELEMENT, ELEMENTS, ELSE, EMPTY, END, ENTRY, EPOCH, ERROR, ESCAPE, EVERY, EXCEPT, EXCLUDE, EXISTS, EXP, EXTRACT, FALSE, FETCH, FILTER, FIRST, FLOOR, FOLLOWING, FOR, FORMAT, FROM, FULL, FUNCTION, GROUP, GROUPS, HAVING, HOUR, ID, IGNORE, ILIKE, IN, INCLUDES, INDEX, INDICES, INNER, INSERT, INSTANT, INTERSECT, INTERSECTS, INTO, IS, JOIN, KEY, LAST, LATERAL, LEADING, LEFT, LIKE, LIMIT, LIST, LISTAGG, LOCAL, LOCAL_DATE, LOCAL_DATETIME, LOCAL_TIME, MAP, MATERIALIZED, MAX, MAXELEMENT, MAXINDEX, MEMBER, MICROSECOND, MILLISECOND, MIN, MINELEMENT, MININDEX, MINUTE, MONTH, NANOSECOND, NATURALID, NEW, NEXT, NO, NOT, NULL, NULLS, OBJECT, OF, OFFSET, OFFSET_DATETIME, ON, ONLY, OR, ORDER, OTHERS, OUTER, OVER, OVERFLOW, OVERLAY, PAD, PARTITION, PERCENT, PLACING, POSITION, POWER, PRECEDING, QUARTER, RANGE, RESPECT, RIGHT, ROLLUP, ROW, ROWS, SEARCH, SECOND, SELECT, SET, SIZE, SOME, SUBSTRING, SUM, THEN, TIES, TIME, TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE, TO, TRAILING, TREAT, TRIM, TRUE, TRUNC, TRUNCATE, TYPE, UNBOUNDED, UNION, UPDATE, USING, VALUE, VALUES, VERSION, VERSIONED, WEEK, WHEN, WHERE, WITH, WITHIN, WITHOUT, YEAR, CHARACTER, STRINGLITERAL, JAVASTRINGLITERAL, INTEGER_LITERAL, FLOAT_LITERAL, HEXLITERAL, BINARY_LITERAL, IDENTIFICATION_VARIABLE}; Bad JPQL grammar [SELECT * FROM DRIVERS WHERE AUDIT_RD IS NOT NULL]
``

Spring boot version 3.2.11

**Comment by isr4el-silv4** [comment]
Facing the same issue as @marcinpiwko , even without returning a list:

```java
@NoRepositoryBean
public interface IUsernamePartRepository<T extends UsernameComponent, ID> extends JpaRepository<T, ID> {


    @Query(value = """
                 SELECT * FROM #{#entityName}
                 WHERE usage = (SELECT MIN(usage) FROM #{#entityName}) ORDER BY random() LIMIT 1
            """
            , nativeQuery = true)
    T findByLowestUsage();
}
```

**Comment by mp911de** [comment]
Care to attach the full stack trace? `nativeQuery=true` switches code paths to SQL processing, however, the exception message mentions JPQL.

**Comment by marcelopbarros** [comment]
Hello @mp911de and maintainers. I'm writing to report that I'm still experiencing this issue in newer versions of Spring Boot. I've tested the provided code snippet in **Spring Boot 3.3.13**, where it runs without any problems. However, the same code fails in **Spring Boot 3.4.8 and 3.5.4** with the same `BadJpqlGrammarException` error.

Here is a simplified code I'm using for testing (spring data, lombok and h2):

```java
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    CommandLineRunner initDatabase(EmployeeRepository repository) {
        return args -> {
            repository.saveAndFlush(Employee.builder().name("Frodo Baggins").build());
            repository.findAll().forEach(System.out::println);
            repository.custom().forEach(System.out::println);
        };
    }
}

@Entity
@Data @Builder
@NoArgsConstructor
@AllArgsConstructor
class Employee {
    @Id @GeneratedValue(strategy = AUTO) private Long id;
    private String name;
}

@Repository
interface EmployeeRepository extends GenericBaseRepository<Employee, Long> {}

@NoRepositoryBean
interface GenericBaseRepository<E, ID> extends JpaRepository<E, ID> {
    @Query(value = "select * from #{#entityName}", nativeQuery = true)
    List<E> custom();
}
```

Could you please consider reopening this issue to investigate this regression?

Thank you for your time and for all the great work you do on this project.

**Comment by mp911de** [comment]
@marcelopbarros please file a new ticket along with the stack trace.
