### ISSUE TITLE
`ParameterBindingParser` fails with `Already found parameter binding with same index`

### ISSUE THREAD

**Issue by kdejaeger** [spring-projects/spring-data-jpa#3126]
Just checked out the release and some unit tests fail.

```
    @Query("SELECT DISTINCT x FROM X x WHERE (COALESCE(:locations) is null OR x.org.id IN :locations)" +
    Set<BLABLA> findABC(@Param("locations") Set<Long> locations);
```

```
Caused by: java.lang.IllegalArgumentException: Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: locations, origin: MethodInvocationArgument[identifier=locations]], found ParameterBinding [identifier: locations, origin: MethodInvocationArgument[identifier=locations]]; If you bind a parameter multiple times make sure they use the same binding
	at org.springframework.util.Assert.isTrue(Assert.java:122)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.lambda$checkAndRegister$8(StringQuery.java:394)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.checkAndRegister(StringQuery.java:394)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.lambda$parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery$0(StringQuery.java:242)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindings.register(StringQuery.java:545)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery(StringQuery.java:308)
```

**Comment by mp911de** [comment]
We've tightened up our comparisons regarding parameter bindings. It seems that the checks for `InParameterBinding` are too strict and we should fix that regression.

**Comment by mp911de** [comment]
That's fixed now and part of the latest snapshots. Care to give it a try with `3.1.4-SNAPSHOT` to see whether the fix works for you?

**Comment by kdejaeger** [comment]
Yes it works, the error is gone now. Thank you.

**Comment by mp911de** [comment]
Fix for regression out of #3041/#3083.

**Comment by HengCC** [comment]
i've update to 3.1.4-snapshot , but problem still , 
https://github.com/spring-projects/spring-data-jpa/issues/1230#issuecomment-1702531236

There is another issue where Hibernate updates the data types of many fields every time it starts. In fact, there have been no actual updates, and no updates are needed. I have replaced the dialect with 'dialect: org.hibernate.dialect.MySQLDialect.'

<img width="581" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/6167532/0ff9c696-d53e-4ad2-a207-8ee4ab1050a2">

**Comment by HengCC** [comment]
After downgrading to version 3.0.9, the field updates mentioned above no longer repeat execution every time the application starts.

> @mp911de i've update to 3.1.4-snapshot , but problem still , [#1230 (comment)](https://github.com/spring-projects/spring-data-jpa/issues/1230#issuecomment-1702531236)
> 
> There is another issue where Hibernate updates the data types of many fields every time it starts. In fact, there have been no actual updates, and no updates are needed. I have replaced the dialect with 'dialect: org.hibernate.dialect.MySQLDialect.'
> 
> <img alt="image" width="581" src="https://user-images.githubusercontent.com/6167532/265001787-0ff9c696-d53e-4ad2-a207-8ee4ab1050a2.png">

**Comment by cec** [comment]
This is still broken in spring-data-jpa 3.2.3!

I spent 1 hour trying to understand what was going on.
In my case I used the short syntax of Postgres to cast (::integer instead of cast(value as integer))
